### PR TITLE
Destructure args in stateless functions

### PR DESCRIPTION
**Pull request by kutyel**
I hate to see blocks with return statements in functions if they can easily be one-liners 😜

---

Nice project btw! 😄

### CODE REVIEW

**Comment by Kikobeats** [comment]
Good catch, I didn't know I can do it 😄

**Comment by kutyel** [comment]
Thanks! Btw, is there any reason that you preferred to use the `createClass` method in the `App` component instead of the `class` syntax? 😕

**Comment by Kikobeats** [comment]
I don't like `class`

**Comment by kutyel** [comment]
😆  good reason! 👍  I haven't checked but I think even @ericelliott uses the class syntax for stateful components (I know you are a fan 😜 )

**Comment by Kikobeats** [comment]
The problem with `class` is binding all time.

```
this.onChange.bind(this.onChange)
```

I feel writing 1997 code using a 2017 functionality.

so, I prefer a plain object for the same, less code, more readable.

Of course It is just an opinion!

**Comment by kutyel** [comment]
True, binding sucks, but I found that sometimes it can be avoided with *class properties* (methods) and *arrow functions*:

This example works:

```jsx
class Sample extends Component {
  state = { hidden: false }
  handleClick = () => this.setState({ hidden: true })
  render = () => (
    <button hidden={this.state.hidden} onClick={this.handleClick}>Hide me!</button>
  ) 
}
```

No `bind` here, and I think it doesn't look that ugly 😉

**Comment by Kikobeats** [comment]
Looks good!

Feel free to open a new PR for removing `createClass` 😄

**Comment by kutyel** [comment]
Sure thing! Done in #3 😆

**Comment by ericelliott** [comment]
Yep, I prefer functional components wherever possible, but if I need lifecycle methods, I use the `class` syntax. I also prefer arrow functions with class props so `this` gets delegated to the instance automatically.

**Pull request merged**
